[build]
builder = "nixpacks"
buildCommand = "cd ../.. && npm install && npm run build:types && npm run build:api"

[deploy]
startCommand = "node apps/api/dist/index.js"
restartPolicyType = "on_failure"
